name: Node.js CI

on:
  push:
    branches: ["**"] # Trigger on push to any branch
  pull_request:
    branches: ["main"] # Trigger on pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
        working-directory: cicd 

      - run: npm run build --if-present
        working-directory: cicd 

      - run: npm test
        working-directory: cicd 

      # Docker-related steps
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: cicd  # Set the context to the correct directory
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demoapp:${{ github.sha }} 

      - name: Deploy to AWS ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "Deploying to ECS..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 905418282509.dkr.ecr.us-east-1.amazonaws.com
          docker build -t demo-app.
          docker tag demo-app:latest 905418282509.dkr.ecr.us-east-1.amazonaws.com/demo-app:latest
          docker push 905418282509.dkr.ecr.us-east-1.amazonaws.com/demo-app:latest
          aws ecs update-service --cluster demo-app-cluster --service demo-app-service --force-new-deployment

