name: Node.js CI

on:
  push:
    branches:
      - "*"  # Runs on all branches
  pull_request:
    branches:
      - main  # Runs on pull requests to main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]  # Node.js version to use

    steps:
    - uses: actions/checkout@v4  # Checkout the repository

    # List all files in the root directory to confirm the structure
    - name: List Files in Root Directory
      run: ls -la

    # List files in the cicd directory to ensure it exists
    - name: List Files in cicd Directory
      run: ls -la cicd

    # Set up Node.js with the version specified in the matrix
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Enable npm caching

    # Install dependencies using npm ci (clean install)
    - run: npm ci
      working-directory: cicd  # Set working directory to 'cicd'

    # Build the project (if there's a build step)
    - run: npm run build --if-present
      working-directory: cicd  # Set working directory to 'cicd'

    # Run tests
    - run: npm test
      working-directory: cicd  # Set working directory to 'cicd'