name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
      working-directory: devops/cicd  # Correct the working directory, without './'

    - run: npm run build --if-present
      working-directory: devops/cicd  # Ensure correct working directory

    - run: npm test
      working-directory: devops/cicd  # Ensure correct working directory
