name: Node.js CI

on:
  push:
    branches:
      - "*"  # Run on every branch push
  pull_request:
    branches:
      - main  # Run on pull request to main branch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4  # Check out the repository code

    # Debug step: Print the current working directory
    - name: Print Working Directory
      run: pwd

    # Debug step: List files in the root directory
    - name: List Files in Root Directory
      run: ls -la

    # After this debug step, check where the 'cicd' folder is located and adjust the paths below
    # accordingly

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Replace 'devops/cicd' with the correct path based on the output from the debug steps above
    - run: npm ci
      working-directory: cicd  # Adjust this if 'cicd' is in a different directory

    - run: npm run build --if-present
      working-directory: cicd  # Adjust this if needed

    - run: npm test
      working-directory: cicd  # Adjust this if needed
