name: Node.js CI

on:
  push:
    branches:
      - "*"  # Run on every branch push
  pull_request:
    branches:
      - main  # Run on pull request to main branch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]  # Node.js version to use

    steps:
    - uses: actions/checkout@v4  # Checkout the repository

    # Debug step to list files in the root directory
    - name: List Files in Root Directory
      run: ls -la

    # Debug step to list files in the 'devops/cicd' directory
    - name: List Files in devops/cicd Directory
      run: ls -la devops/cicd

    # Set up Node.js with the version specified in the matrix
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Enable npm caching

    # Install dependencies using npm ci (clean install)
    - run: npm ci
      working-directory: devops/cicd  # Set working directory to 'devops/cicd'

    # Build the project (if there's a build step)
    - run: npm run build --if-present
      working-directory: devops/cicd  # Set working directory to 'devops/cicd'

    # Run tests
    - run: npm test
      working-directory: devops/cicd  # Set working directory to 'devops/cicd'
