name: Node.js CI

on:
  # Triggers the workflow on any push to any branch
  push:
    branches:
      - "*"  # This will trigger for all branches

  # Triggers the workflow when a pull request is opened or merged into the 'main' branch
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Print Working Directory
      run: pwd  # Debug step to print the current working directory

    - name: List Files in Current Directory
      run: ls -la  # Debug step to list files in the root directory

    - name: List Files in DevOps Directory
      run: ls -la devops  # Debug step to list files in the devops directory to verify 'cicd'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
      working-directory: devops/cicd  # Ensure the correct path

    - run: npm run build --if-present
      working-directory: devops/cicd

    - run: npm test
      working-directory: devops/cicd
